name: "go-binance-bot"
trades:
  - symbol: "BTC/USDT"
    interval: "5m"
    buyPrice: 34322.0
    sellPrice: 50640.0
  - symbol: "LOKA/USDT"
    interval: "5m"
    buyPrice: 3.51
    sellPrice: 4.01
  - symbol: "TRIBE/USDT"
    interval: "5m"
    buyPrice: 0.58
    sellPrice: 0.60
  - symbol: "IOTA/USDT"
    interval: "1m"
    buyPrice: 0.80
    sellPrice: 0.90
  - symbol: "WAVES/USDT"
    interval: "5m"
    buyPrice: 30.20
    sellPrice: 53.31
  - symbol: "XRP/USDT"
    interval: "5m"
    buyPrice: 0.80
    sellPrice: 0.82
