name: "go-binance-bot"
trades:
  - symbol: "LOKA/USDT"
    interval: "5m"
    buyPrice: 3.51
    sellPrice: 4.01
  - symbol: "TRIBE/USDT"
    interval: "5m"
    buyPrice: 0.58
    sellPrice: 0.60
  - symbol: "IOTA/USDT"
    interval: "1m"
    buyPrice: 0.76
    sellPrice: 0.90
  - symbol: "WAVES/USDT"
    interval: "5m"
    buyPrice: 27.22
    sellPrice: 30.20
  - symbol: "XRP/USDT"
    interval: "5m"
    buyPrice: 0.80
    sellPrice: 0.82
